apiVersion: apps/v1
kind: Deployment
metadata:
  name: will42
spec:
  replicas: 1
  selector:
    matchLabels:
      app: will42
  template:
    metadata:
      labels:
        app: will42
    spec:
      containers:
        - name: will42
          image: wil42/playground:v1
          ports:
            - name: http-port
              containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: will42-service
spec:
  selector:
    app: will42
  ports:
    - name: app
      port: 80
      targetPort: 8080