apiVersion: apps/v1
kind: Deployment
metadata:
  name: will42-app
  labels:
    app: will42-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: will42-app
  template:
    metadata:
      labels:
        app: will42-app
    spec:
      containers:
        - name: will42-app
          image: wil42/playground:v2
          ports:
            - name: http-port
              containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: will42-app
spec:
  selector:
    app: will42-app
  ports:
    - name: app
      port: 80
      targetPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: will42-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: will42-app
            port:
              number: 80